In [205]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Predict Loan Eligibility for Dream Housing Finance company
Dream Housing Finance company deals in all kinds of home loans. They have presence across all urban, semi urban and rural areas. Customer first applies for home loan and after that company validates the customer eligibility for loan.

Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form. These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others. To automate this process, they have provided a dataset to identify the customers segments that are eligible for loan amount so that they can specifically target these customers.

In [206]:
# load the datasets

train_df = pd.read_csv('/content/train_ctrUa4K.csv')
test_df = pd.read_csv('/content/test_lAUu6dG.csv')

In [207]:
train_df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [208]:
train_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [209]:
train_df.shape

(614, 13)

In [210]:
test_df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

In [211]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [212]:
train_df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [213]:
# checking missing values in trainning data

train_df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [214]:
test_df.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [215]:
# handling missing values
# catogorical variables

from sklearn.impute import SimpleImputer

categorical_imputer = SimpleImputer(strategy='most_frequent')

train_df[['Gender','Married','Dependents','Self_Employed']] = categorical_imputer.fit_transform(train_df[['Gender','Married','Dependents','Self_Employed']])

test_df[['Gender','Married','Dependents','Self_Employed']] = categorical_imputer.fit_transform(test_df[['Gender','Married','Dependents','Self_Employed']])

In [216]:
# fitting missing values in credit history

train_df['Credit_History'] = categorical_imputer.fit_transform(train_df[['Credit_History']])
test_df['Credit_History'] = categorical_imputer.fit_transform(test_df[['Credit_History']])

In [217]:
# Numericall variables

numeric_imputer = SimpleImputer(strategy='median')

train_df[['LoanAmount','Loan_Amount_Term']] = numeric_imputer.fit_transform(train_df[['LoanAmount','Loan_Amount_Term']])
test_df[['LoanAmount','Loan_Amount_Term']] = numeric_imputer.fit_transform(test_df[['LoanAmount','Loan_Amount_Term']])

In [218]:
train_df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [219]:
test_df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [220]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [221]:
# encoding categorical columns

#one hot encoding


train_df_encoded = pd.get_dummies(train_df, columns=['Gender','Married','Dependents','Education','Self_Employed','Property_Area'])
test_df_encoded = pd.get_dummies(test_df, columns=['Gender','Married','Dependents','Education','Self_Employed','Property_Area'])

#ensuring that both training and test datasets have same columns

test_df_encoded = test_df.reindex(columns=train_df_encoded.columns, fill_value=0)

In [222]:
# label encoding for target variable

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

train_df_encoded['Loan_Status'] = label_encoder.fit_transform(train_df_encoded['Loan_Status'])
test_df_encoded['Loan_Status'] = label_encoder.fit_transform(test_df_encoded['Loan_Status'])

In [223]:
train_df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Loan_ID                  614 non-null    object
 1   ApplicantIncome          614 non-null    int64
 2   CoapplicantIncome        614 non-null    float64
 3   LoanAmount               614 non-null    float64
 4   Loan_Amount_Term         614 non-null    float64
 5   Credit_History           614 non-null    float64
 6   Loan_Status              614 non-null    int64
 7   Gender_Female            614 non-null    bool
 8   Gender_Male              614 non-null    bool
 9   Married_No               614 non-null    bool
 10  Married_Yes              614 non-null    bool
 11  Dependents_0             614 non-null    bool
 12  Dependents_1             614 non-null    bool
 13  Dependents_2             614 non-null    bool
 14  Dependents_3+            614 non-null    bool
 15  Education_Graduate       614 non-null    bool
 16  Education_Not Graduate   614 non-null    bool
 17  Self_Employed_No         614 non-null    bool
 18  Self_Employed_Yes        614 non-null    bool
 19  Property_Area_Rural      614 non-null    bool
 20  Property_Area_Semiurban  614 non-null    bool
 21  Property_Area_Urban      614 non-null    bool
dtypes: bool(15), float64(4), int64(2), object(1)
memory usage: 42.7+ KB

In [224]:
#converting boolean columns into integers for better learning

boolean_columns = ['Gender_Female','Gender_Male','Married_No', 'Married_Yes','Dependents_0','Dependents_1','Dependents_2', 'Dependents_3+','Education_Graduate', 'Education_Not Graduate', 'Self_Employed_Yes','Self_Employed_No', 'Property_Area_Rural', 'Property_Area_Semiurban','Property_Area_Urban']
for col in boolean_columns:
  train_df_encoded[col] = train_df_encoded[col].astype(int)

In [225]:
train_df_encoded.dtypes

Loan_ID                     object
ApplicantIncome              int64
CoapplicantIncome          float64
LoanAmount                 float64
Loan_Amount_Term           float64
Credit_History             float64
Loan_Status                  int64
Gender_Female                int64
Gender_Male                  int64
Married_No                   int64
Married_Yes                  int64
Dependents_0                 int64
Dependents_1                 int64
Dependents_2                 int64
Dependents_3+                int64
Education_Graduate           int64
Education_Not Graduate       int64
Self_Employed_No             int64
Self_Employed_Yes            int64
Property_Area_Rural          int64
Property_Area_Semiurban      int64
Property_Area_Urban          int64
dtype: object

In [226]:
train_df_encoded

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128.0,360.0,1.0,1,0,1,1,...,0,0,0,1,0,1,0,0,0,1
1,LP001003,4583,1508.0,128.0,360.0,1.0,0,0,1,0,...,1,0,0,1,0,1,0,1,0,0
2,LP001005,3000,0.0,66.0,360.0,1.0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,1
3,LP001006,2583,2358.0,120.0,360.0,1.0,1,0,1,0,...,0,0,0,0,1,1,0,0,0,1
4,LP001008,6000,0.0,141.0,360.0,1.0,1,0,1,1,...,0,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,2900,0.0,71.0,360.0,1.0,1,1,0,1,...,0,0,0,1,0,1,0,1,0,0
610,LP002979,4106,0.0,40.0,180.0,1.0,1,0,1,0,...,0,0,1,1,0,1,0,1,0,0
611,LP002983,8072,240.0,253.0,360.0,1.0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
612,LP002984,7583,0.0,187.0,360.0,1.0,1,0,1,0,...,0,1,0,1,0,1,0,0,0,1
613,LP002990,4583,0.0,133.0,360.0,0.0,0,1,0,1,...,0,0,0,1,0,0,1,0,1,0

In [227]:
train_df_encoded.value_counts('Loan_Amount_Term')

Loan_Amount_Term
360.0    526
180.0     44
480.0     15
300.0     13
84.0       4
240.0      4
120.0      3
36.0       2
60.0       2
12.0       1
Name: count, dtype: int64

In [228]:
# scaling for numerical values
#standardization


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']] = scaler.fit_transform(train_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']])
test_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']] = scaler.fit_transform(test_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']])

In [229]:
train_df_encoded

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0.072991,-0.554487,-0.211241,0.273231,1.0,1,0,1,1,...,0,0,0,1,0,1,0,0,0,1
1,LP001003,-0.134412,-0.038732,-0.211241,0.273231,1.0,0,0,1,0,...,1,0,0,1,0,1,0,1,0,0
2,LP001005,-0.393747,-0.554487,-0.948996,0.273231,1.0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,1
3,LP001006,-0.462062,0.251980,-0.306435,0.273231,1.0,1,0,1,0,...,0,0,0,0,1,1,0,0,0,1
4,LP001008,0.097728,-0.554487,-0.056551,0.273231,1.0,1,0,1,1,...,0,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,-0.410130,-0.554487,-0.889500,0.273231,1.0,1,1,0,1,...,0,0,0,1,0,1,0,1,0,0
610,LP002979,-0.212557,-0.554487,-1.258378,-2.522836,1.0,1,0,1,0,...,0,0,1,1,0,1,0,1,0,0
611,LP002983,0.437174,-0.472404,1.276168,0.273231,1.0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
612,LP002984,0.357064,-0.554487,0.490816,0.273231,1.0,1,0,1,0,...,0,1,0,1,0,1,0,0,0,1
613,LP002990,-0.134412,-0.554487,-0.151745,0.273231,0.0,0,1,0,1,...,0,0,0,1,0,0,1,0,1,0

In [230]:
train_df_encoded.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,Married_Yes,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
count,6.140000e+02,6.140000e+02,6.140000e+02,6.140000e+02,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,...,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,-4.339634e-18,4.050325e-17,-2.603780e-17,5.930833e-17,0.855049,0.687296,0.182410,0.817590,0.346906,0.653094,...,0.166124,0.164495,0.083062,0.781759,0.218241,0.866450,0.133550,0.291531,0.379479,0.328990
std,1.000815e+00,1.000815e+00,1.000815e+00,1.000815e+00,0.352339,0.463973,0.386497,0.386497,0.476373,0.476373,...,0.372495,0.371027,0.276201,0.413389,0.413389,0.340446,0.340446,0.454838,0.485653,0.470229
min,-8.606493e-01,-5.544873e-01,-1.627255e+00,-5.132498e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-4.138159e-01,-5.544873e-01,-5.414462e-01,2.732313e-01,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,-2.606393e-01,-1.480047e-01,-2.112412e-01,2.732313e-01,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,6.414426e-02,2.312023e-01,2.260572e-01,2.732313e-01,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000
max,1.238462e+01,1.369617e+01,6.595146e+00,2.137276e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [231]:
# spliting the data

from sklearn.model_selection import train_test_split

X = train_df_encoded.drop(['Loan_ID','Loan_Status'],axis=1)
y = train_df_encoded['Loan_Status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


MODELLING

In [232]:
#Logistic regression

from sklearn.linear_model import LogisticRegression
logit_model = LogisticRegression()
logit_model.fit(X_train, y_train)
y_pred = logit_model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score


print("Accuracy:", accuracy_score(y_test, y_pred))
print('precision:', precision_score(y_test, y_pred))
print('recall:', recall_score(y_test, y_pred))
print('f1 score:', f1_score(y_test, y_pred))

Accuracy: 0.7886178861788617
precision: 0.7596153846153846
recall: 0.9875
f1 score: 0.8586956521739131

In [233]:
print('confusion matrix:', confusion_matrix(y_test, y_pred))
print('classification report:', classification_report(y_test, y_pred))

confusion matrix: [[18 25]
 [ 1 79]]
classification report:               precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123

KNN

In [234]:
# knn

from sklearn.neighbors import KNeighborsClassifier
metric_k =[]
neighbors = np.arange(3,15)
for k in neighbors:
  knn_model = KNeighborsClassifier(n_neighbors=k)
  knn_model.fit(X_train, y_train)
  y_pred = knn_model.predict(X_test)
  acc = accuracy_score(y_test, y_pred)
  metric_k.append(acc)

In [235]:
metric_k

[0.7154471544715447,
 0.6747967479674797,
 0.7073170731707317,
 0.6747967479674797,
 0.7235772357723578,
 0.6910569105691057,
 0.7073170731707317,
 0.6829268292682927,
 0.6910569105691057,
 0.6829268292682927,
 0.6747967479674797,
 0.6747967479674797]

In [236]:
knn_model = KNeighborsClassifier(n_neighbors=5, metric= 'minkowski', p=2)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print('precision:', precision_score(y_test, y_pred))
print('recall:', recall_score(y_test, y_pred))
print('f1 score:', f1_score(y_test, y_pred))

Accuracy: 0.7073170731707317
precision: 0.7075471698113207
recall: 0.9375
f1 score: 0.8064516129032258

SVM

In [237]:
from sklearn.svm import SVC
sv_clf = SVC()
sv_clf.fit(X_train,y_train)

SVC()

In [238]:
y_pred = sv_clf.predict(X_test)

print("accuracy is ", accuracy_score(y_test,y_pred))
print("precision is ", precision_score(y_test,y_pred,average='micro'))
print("recall is ", recall_score(y_test,y_pred,average='micro'))
print("f1 score is ", f1_score(y_test,y_pred,average='micro'))

accuracy is  0.7886178861788617
precision is  0.7886178861788617
recall is  0.7886178861788617
f1 score is  0.7886178861788617

DECISION TREE

In [239]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state= 42)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [240]:
y_pred = dt_clf.predict(X_test)

print("accuracy is ", accuracy_score(y_test,y_pred))
print("precision is ", precision_score(y_test,y_pred,average='micro'))
print("recall is ", recall_score(y_test,y_pred,average='micro'))
print("f1 score is ", f1_score(y_test,y_pred,average='micro'))

accuracy is  0.7154471544715447
precision is  0.7154471544715447
recall is  0.7154471544715447
f1 score is  0.7154471544715447

RANDOM FOREST DECISION TREE

In [241]:

from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train,y_train)

RandomForestClassifier()

In [242]:
y_pred = rf_clf.predict(X_test)

print("accuracy is ", accuracy_score(y_test,y_pred))
print("precision is ", precision_score(y_test,y_pred,average='micro'))
print("recall is ", recall_score(y_test,y_pred,average='micro'))
print("f1 score is ", f1_score(y_test,y_pred,average='micro'))

accuracy is  0.7560975609756098
precision is  0.7560975609756098
recall is  0.7560975609756098
f1 score is  0.7560975609756099

HYPER PARAMETER TUNING

In [243]:
# HYPER PARAMETER TUNING

rf_clf1 = RandomForestClassifier(criterion='Entropy', n_estimators=20)

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train,y_train)

y_pred = rf_clf.predict(X_test)


print("accuracy is ", accuracy_score(y_test,y_pred))
print("precision is ", precision_score(y_test,y_pred,average='micro'))
print("recall is ", recall_score(y_test,y_pred,average='micro'))
print("f1 score is ", f1_score(y_test,y_pred,average='micro'))

accuracy is  0.7642276422764228
precision is  0.7642276422764228
recall is  0.7642276422764228
f1 score is  0.7642276422764228

### logistic regression gives the best **value**

PREDICTIONS

In [255]:
test_df.head()

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,ApplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_ID
0,1,1,0,1,0,1,5500,110,360,1,101
1,0,0,1,0,1,0,6200,160,120,0,102

In [256]:
test_df.isnull().sum()

Gender              0
Married             0
Dependents          0
Education           0
Self_Employed       0
Property_Area       0
ApplicantIncome     0
LoanAmount          0
Loan_Amount_Term    0
Credit_History      0
Loan_ID             0
dtype: int64

In [257]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            2 non-null      int64
 1   Married           2 non-null      int64
 2   Dependents        2 non-null      int64
 3   Education         2 non-null      int64
 4   Self_Employed     2 non-null      int64
 5   Property_Area     2 non-null      int64
 6   ApplicantIncome   2 non-null      int64
 7   LoanAmount        2 non-null      int64
 8   Loan_Amount_Term  2 non-null      int64
 9   Credit_History    2 non-null      int64
 10  Loan_ID           2 non-null      int64
dtypes: int64(11)
memory usage: 304.0 bytes

In [258]:
test_df[['Gender','Married','Dependents','Self_Employed']] = categorical_imputer.fit_transform(test_df[['Gender','Married','Dependents','Self_Employed']])

test_df['Credit_History'] = categorical_imputer.fit_transform(test_df[['Credit_History']])

test_df[['LoanAmount','Loan_Amount_Term']] = numeric_imputer.fit_transform(test_df[['LoanAmount','Loan_Amount_Term']])

test_df_encoded = test_df.reindex(columns=train_df_encoded.columns, fill_value=0)


test_df_encoded['Loan_Status'] = label_encoder.fit_transform(test_df_encoded['Loan_Status'])

test_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']] = scaler.fit_transform(test_df_encoded[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']])

In [259]:
X_test = test_df_encoded.drop(['Loan_ID','Loan_Status'],axis=1)

In [262]:
y_pred_log = logit_model.predict(X_test)

In [263]:
y_pred_log

array([1, 0])

In [264]:
y_pred_final = np.where(y_pred_log == 1, 'Y', 'N')

In [265]:
y_pred_final

array(['Y', 'N'], dtype='<U1')

# Load Sample submission file

In [270]:
df3 = pd.read_csv('/content/sample_submission_49d68Cx.csv')

In [271]:
df3.head()

    Loan_ID Loan_Status
0  LP001015           N
1  LP001022           N
2  LP001031           N
3  LP001035           N
4  LP001051           N

In [275]:
df_final = pd.DataFrame({'Loan_ID': test_df['Loan_ID'], 'Loan_Status': y_pred_final})

In [276]:
df_final.head()

   Loan_ID Loan_Status
0      101           Y
1      102           N

In [277]:
df_final.to_csv("sample_submission_49d68Cx.csv", index=False)